title: Parameters
required:
  - title
  - bodyText
  - callToAction
type: object
properties:
  title:
    type: string
  bodyText:
    type: string
  callToAction:
    type: string
example:
  title: This is a title
  bodyText: This is some body text
  callToAction: http://www.example.com/
